runtime bundle/vim-pathogen/autoload/pathogen.vim

set ruler

set backspace=indent,eol,start

set ignorecase
set smartcase
set incsearch
set hlsearch

set wildmode=list:longest,full

set number

set autowrite

set updatecount=10

set autoindent
set smartindent

set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

set autochdir

set pastetoggle=<F2>

let g:NERDTreeDirArrows=0

call pathogen#infect()

syntax enable 
filetype on
filetype plugin indent on

if has("gui_running")
    colorscheme wombat

    set guioptions-=m
    set guioptions-=T

    set cursorline
else
    set t_Co=256
    colorscheme wombat256mod
endif

" set up syntax highlighting for my e-mail
au BufRead,BufNewFile .followup,.article,.letter,/tmp/pico*,nn.*,snd.*,/tmp/mutt* :set ft=mail

au FileType xml exe ":silent 1,$!xmllint --format --recover - 2>/dev/null"

let twitvim_enable_python = 1
let twitvim_browser_cmd = '/usr/bin/chromium-browser'

nmap <slient> <BS> :nohlsearch<CR>

noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

augroup HelpInTabs
    au!
    au BufEnter *.txt call HelpInNewTab()
    
    function! HelpInNewTab ()
        if &buftype == 'help'
            execute "normal \<C-W>T"
        endif
    endfunction
augroup END

" pep 8
let g:pep8_map='<leader>8'

" supertab
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

" Space to tab
:command! -range=% -nargs=0 Tab2Space execute '<line1>,<line2>s#^\t\+#\=repeat(" ", len(submatch(0))*' . &ts . ')'
:command! -range=% -nargs=0 Space2Tab execute '<line1>,<line2>s#^\( \{'.&ts.'\}\)\+#\=repeat("\t", len(submatch(0))/' . &ts . ')'

" vimdiff keymappings
if &diff
    noremap <space> ]cz.
    noremap <S-space> [cz.]
endif

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType python set complete+=k~/.vim/syntax/python.vim isk+=.,(
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
