runtime bundle/vim-pathogen/autoload/pathogen.vim

set ruler
set autoread
set scrolloff=3
set backspace=indent,eol,start
set ignorecase
set smartcase
set incsearch
set hlsearch
set wildmode=list:longest,full
set number
set autowrite
set updatecount=10
set autoindent
set smartindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autochdir

let g:NERDTreeDirArrows=0
let NERDTreeShowHidden=0
let g:syntastic_javascript_checkers = ['jshint']
let g:gitgutter_enabled = 0

call pathogen#infect()

syntax enable 
filetype on
filetype plugin indent on

if has("gui_running")
    colorscheme wombat

    set guioptions-=m
    set guioptions-=T

    set cursorline
else
    set t_Co=256
    colorscheme wombat256mod
endif

" set up syntax highlighting for my e-mail
au BufRead,BufNewFile .followup,.article,.letter,/tmp/pico*,nn.*,snd.*,/tmp/mutt* :set ft=mail

au FileType xml exe ":silent 1,$!xmllint --format --recover - 2>/dev/null"

let twitvim_enable_python = 1
let twitvim_browser_cmd = '/usr/bin/chromium-browser'

let mapleader = ','
nmap <silent> <BS> :nohlsearch<CR>
nmap <leader>d :NERDTreeToggle<CR>
nmap <leader>g :GitGutterToggle<CR>
map <leader>l :Align
map <leader>p :set paste<CR>
map <leader>pp :set nopaste<CR>


nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

augroup HelpInTabs
    au!
    au BufEnter *.txt call HelpInNewTab()
    
    function! HelpInNewTab ()
        if &buftype == 'help'
            execute "normal \<C-W>T"
        endif
    endfunction
augroup END

" pep 8
let g:pep8_map='<leader>8'

" supertab
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

" Space to tab
:command! -range=% -nargs=0 Tab2Space execute '<line1>,<line2>s#^\t\+#\=repeat(" ", len(submatch(0))*' . &ts . ')'
:command! -range=% -nargs=0 Space2Tab execute '<line1>,<line2>s#^\( \{'.&ts.'\}\)\+#\=repeat("\t", len(submatch(0))/' . &ts . ')'

" vimdiff keymappings
if &diff
    noremap <space> ]cz.
    noremap <S-space> [cz.]
endif

autocmd BufRead,BufNewFile *.md set filetype=markdown

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType python set complete+=k~/.vim/syntax/python.vim isk+=.,(
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS shiftwidth=2 tabstop=2
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags 
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
