#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias vi=vim
alias python=/usr/bin/python2

# Python VirtualEnv
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='-p python2.7'
source /usr/bin/virtualenvwrapper.sh

# Ruby Path
export PATH=$PATH:~/.gem/ruby/1.9.1/bin

# Heroku Path
export PATH="/usr/local/heroku/bin:$PATH"

if [ -n "$DISPLAY" ]; then
    BROWSER=chromium
fi
