#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias vi=vim

# TODO.SH Stuff
alias t=todo.sh
export TODOTXT_DEFAULT_ACTION=ls
export TODOTXT_SORT_COMMAND='env LC_COLLATE=C sort -k 2,2 -k 1,1n'

# Python VirtualEnv
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

if [[ -z $DISPLAY && $(tty) = /dev/tty1 ]]; then
	exec startx
fi
